# Jekyll config per GitHub Pages
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Applica il layout "default" a tutte le pagine in /docs
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
